//! G-code emission for a generic configurable FDM printer profile.
//!
//! SPDX-License-Identifier: MIT OR Apache-2.0
//!
//! Produces Marlin/Klipper-style G-code (absolute coordinates, `E` extrusion in
//! mm) from a sequence of [`LayerPlan`]s, honouring the printer profile and
//! material calibration (flow ratio, temperatures, cooling).

use crate::path::{LayerPlan, Move};
use crate::profile::{MaterialCalibration, PrinterProfile};
use crate::layers::P2;

/// Result of G-code emission: the textual program plus simple metadata.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct GCode {
    pub text: String,
    pub layer_count: usize,
    pub estimated_filament_mm: f64,
    pub estimated_time_s: f64,
}

/// Emit G-code for the given layer plans.
pub fn emit_gcode(
    plans: &[LayerPlan],
    printer: &PrinterProfile,
    material: &MaterialCalibration,
) -> GCode {
    let mut text = String::new();
    let width = printer.extrusion_width();
    let fil_area = printer.filament_area();
    let mut e_total = 0.0;
    let mut time_s = 0.0;

    // --- Header / start G-code ---
    let nozzle_t = material.nozzle_temperature(printer.nozzle_temperature);
    let bed_t = material.bed_temperature(printer.bed_temperature);
    text.push_str("; Generated by tpt-vertex-slicer\n");
    text.push_str(&format!("; Printer: {}\n", printer.name));
    text.push_str(&format!("; Material: {}\n", material.name));
    text.push_str("G90 ; absolute coordinates\n");
    text.push_str("M82 ; absolute extrusion\n");
    text.push_str("G21 ; millimetres\n");
    text.push_str(&format!("M104 S{:.1} ; set hotend temp\n", nozzle_t));
    text.push_str(&format!("M140 S{:.1} ; set bed temp\n", bed_t));
    text.push_str("G28 ; home\n");
    text.push_str("G1 Z0.2 F300 ; lift to first layer\n");
    text.push_str(&format!("M109 S{:.1} ; wait for hotend\n", nozzle_t));
    text.push_str(&format!("M190 S{:.1} ; wait for bed\n", bed_t));

    let mut last: Option<P2> = None;
    let mut last_z = 0.0;

    for plan in plans {
        text.push_str(&format!("; LAYER Z={:.3}\n", plan.z));
        text.push_str(&format!("G1 Z{:.3} F{:.0}\n", plan.z, printer.travel_speed * 60.0));

        for m in &plan.moves {
            match m {
                Move::Travel { to, z, retract, z_hop } => {
                    if *retract {
                        e_total -= printer.retraction_length;
                        text.push_str(&format!(
                            "G1 E{:.4} F{:.0} ; retract\n",
                            e_total,
                            printer.retraction_speed * 60.0
                        ));
                    }
                    if *z_hop {
                        text.push_str(&format!(
                            "G1 Z{:.3} F{:.0} ; z-hop\n",
                            *z + printer.z_hop,
                            printer.travel_speed * 60.0
                        ));
                    }
                    text.push_str(&format!(
                        "G0 X{:.3} Y{:.3} F{:.0}\n",
                        to.x,
                        to.y,
                        printer.travel_speed * 60.0
                    ));
                    if *z_hop {
                        text.push_str(&format!(
                            "G1 Z{:.3} F{:.0} ; z-unhop\n",
                            *z,
                            printer.travel_speed * 60.0
                        ));
                    }
                    if *retract {
                        e_total += printer.retraction_length;
                        text.push_str(&format!(
                            "G1 E{:.4} F{:.0} ; unretract\n",
                            e_total,
                            printer.retraction_speed * 60.0
                        ));
                    }
                    last = Some(*to);
                    last_z = *z;
                }
                Move::Extrude { path, z } => {
                    if let Some(first) = path.points.first() {
                        if last.map_or(true, |p| p.dist(*first) > 1e-6) {
                            text.push_str(&format!(
                                "G1 X{:.3} Y{:.3} F{:.0}\n",
                                first.x,
                                first.y,
                                printer.travel_speed * 60.0
                            ));
                        }
                    }
                    let mut prev = *path.points.first().unwrap();
                    // Bead height = this layer's thickness (delta from previous Z).
                    let layer_h = (plan.z - last_z).abs().max(0.01);
                    for &p in path.points.iter().skip(1) {
                        let d = prev.dist(p);
                        if d < 1e-9 {
                            prev = p;
                            continue;
                        }
                        let bead = width * layer_h;
                        let mut seg_e = (bead * d) / fil_area;
                        seg_e = material.scale_extrusion(seg_e);
                        e_total += seg_e;
                        text.push_str(&format!(
                            "G1 X{:.3} Y{:.3} E{:.4} F{:.0}\n",
                            p.x,
                            p.y,
                            e_total,
                            printer.print_speed * 60.0
                        ));
                        time_s += d / printer.print_speed;
                        prev = p;
                    }
                    last = path.points.last().copied();
                    last_z = *z;
                }
            }
        }
    }

    // --- End G-code ---
    text.push_str("M104 S0 ; hotend off\n");
    text.push_str("M140 S0 ; bed off\n");
    text.push_str("G1 Z300 F300 ; present\n");
    text.push_str("M84 ; motors off\n");

    GCode {
        text,
        layer_count: plans.len(),
        estimated_filament_mm: e_total.max(0.0),
        estimated_time_s: time_s,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::path::{ExtrusionPath, Move};

    #[test]
    fn emits_header_and_extrusion() {
        let printer = PrinterProfile::default();
        let mat = MaterialCalibration::default();
        let plan = LayerPlan {
            z: 0.2,
            moves: vec![Move::Extrude {
                z: 0.2,
                path: ExtrusionPath {
                    closed: true,
                    points: vec![
                        P2::new(0.0, 0.0),
                        P2::new(10.0, 0.0),
                        P2::new(10.0, 10.0),
                        P2::new(0.0, 10.0),
                    ],
                },
            }],
        };
        let g = emit_gcode(&[plan], &printer, &mat);
        assert!(g.text.contains("G90"));
        assert!(g.text.contains("G1 X"));
        assert!(g.text.contains("E"));
        assert_eq!(g.layer_count, 1);
        assert!(g.estimated_filament_mm > 0.0);
    }
}
