//! Infill generation: rectilinear and zigzag fill inside a region.
//!
//! SPDX-License-Identifier: MIT OR Apache-2.0
//!
//! Infill is generated by scanning parallel lines across the bounding box of a
//! region (the innermost wall contour) and clipping each line to the polygon.
//! Density controls the spacing between scan lines.

use crate::layers::{Contour, P2};

/// A polyline path (possibly open) used for infill lines.
#[derive(Debug, Clone, PartialEq)]
pub struct InfillLine {
    pub a: P2,
    pub b: P2,
}

/// Generate infill lines for `region` (the innermost wall, treated as the fill
/// boundary) at the given `density` (0..=1) and `line_spacing` (mm, full spacing
/// between adjacent scan lines at density 1).
///
/// `zigzag` alternates scan direction per line; otherwise every line runs the
/// same direction (rectilinear). `angle_deg` orients the scan grid.
pub fn generate_infill(
    region: &Contour,
    density: f64,
    line_spacing: f64,
    zigzag: bool,
    angle_deg: f64,
) -> Vec<InfillLine> {
    let density = density.clamp(0.0, 1.0);
    if density <= 0.0 {
        return Vec::new();
    }
    let spacing = (line_spacing / density).max(1e-3);
    let Some(bbox) = region.bbox() else {
        return Vec::new();
    };
    let ((minx, miny), (maxx, maxy)) = bbox;
    let ang = angle_deg.to_radians();
    let dir = (ang.cos(), ang.sin());
    let perp = (-dir.1, dir.0);

    // Project all region points onto the scan-axis (perp direction) to find the
    // range of scan positions, then step along it.
    let proj = |p: P2| p.x * perp.0 + p.y * perp.1;
    let mut tmin = f64::INFINITY;
    let mut tmax = f64::NEG_INFINITY;
    for p in &region.points {
        let t = proj(*p);
        tmin = tmin.min(t);
        tmax = tmax.max(t);
    }

    let to_world = |along: f64, across: f64| -> P2 {
        // world = dir*along + perp*across
        P2::new(
            dir.0 * along + perp.0 * across,
            dir.1 * along + perp.1 * across,
        )
    };

    let mut lines = Vec::new();
    let mut flip = false;
    let mut t = tmin;
    // Safety cap: bounds the work if a degenerate region slips through.
    let max_lines = ((tmax - tmin) / spacing).ceil().max(0.0) as usize + 2;
    let max_lines = max_lines.min(100_000);
    let mut count = 0usize;
    while t <= tmax + 1e-9 && count < max_lines {
        count += 1;
        // The scan line runs along `dir` across the full bbox extent.
        let (amin, amax) = (minx * dir.0 + miny * dir.1, maxx * dir.0 + maxy * dir.1)
            .minmax();
        let mut a = to_world(amin, t);
        let mut b = to_world(amax, t);
        if zigzag && flip {
            std::mem::swap(&mut a, &mut b);
        }
        flip = !flip;
        if let Some(clipped) = clip_line_to_polygon(region, a, b, dir) {
            lines.push(clipped);
        }
        t += spacing;
    }
    lines
}

/// Clip a segment `[a,b]` running along `dir` to the portion inside `poly`.
/// Returns the clipped sub-segment, or `None` if fully outside.
fn clip_line_to_polygon(
    poly: &Contour,
    a: P2,
    b: P2,
    _dir: (f64, f64),
) -> Option<InfillLine> {
    let n = poly.points.len();
    if n < 3 {
        return None;
    }
    // Parametric intersection of segment with each polygon edge; keep t in [0,1]
    // that lie inside (even-odd point-in-polygon test on the segment endpoints).
    let seg_dx = b.x - a.x;
    let seg_dy = b.y - a.y;
    let seg_len2 = seg_dx * seg_dx + seg_dy * seg_dy;
    if seg_len2 < 1e-18 {
        return None;
    }

    let mut ts: Vec<f64> = vec![0.0, 1.0];
    for i in 0..n {
        let p = poly.points[i];
        let q = poly.points[(i + 1) % n];
        let ex = q.x - p.x;
        let ey = q.y - p.y;
        let denom = seg_dx * ey - seg_dy * ex;
        if denom.abs() < 1e-12 {
            continue;
        }
        let t = ((p.x - a.x) * ey - (p.y - a.y) * ex) / denom;
        if t >= -1e-9 && t <= 1.0 + 1e-9 {
            ts.push(t.clamp(0.0, 1.0));
        }
    }
    ts.sort_by(|x, y| x.partial_cmp(y).unwrap());
    // Drop duplicate intersection parameters to avoid zero-length spans.
    ts.dedup_by(|a, b| (*a - *b).abs() < 1e-9);

    // Among interior spans, return the first one that is inside the polygon.
    for w in ts.windows(2) {
        if (w[1] - w[0]).abs() < 1e-9 {
            continue;
        }
        let mid = (w[0] + w[1]) / 2.0;
        let px = a.x + mid * seg_dx;
        let py = a.y + mid * seg_dy;
        if point_in_polygon(poly, P2::new(px, py)) {
            return Some(InfillLine {
                a: P2::new(a.x + w[0] * seg_dx, a.y + w[0] * seg_dy),
                b: P2::new(a.x + w[1] * seg_dx, a.y + w[1] * seg_dy),
            });
        }
    }
    None
}

fn point_in_polygon(poly: &Contour, p: P2) -> bool {
    let n = poly.points.len();
    let mut inside = false;
    for i in 0..n {
        let a = poly.points[i];
        let b = poly.points[(i + 1) % n];
        if ((a.y > p.y) != (b.y > p.y))
            && (p.x < (b.x - a.x) * (p.y - a.y) / (b.y - a.y) + a.x)
        {
            inside = !inside;
        }
    }
    inside
}

trait MinMax {
    fn minmax(self) -> (f64, f64);
}
impl MinMax for (f64, f64) {
    fn minmax(self) -> (f64, f64) {
        (self.0.min(self.1), self.0.max(self.1))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn square(s: f64) -> Contour {
        Contour {
            points: vec![
                P2::new(-s, -s),
                P2::new(s, -s),
                P2::new(s, s),
                P2::new(-s, s),
            ],
        }
    }

    #[test]
    fn rectilinear_covers_unit_square() {
        let c = square(1.0);
        let lines = generate_infill(&c, 1.0, 0.25, false, 0.0);
        // Full density at 0.25 spacing over a 2-unit span => ~9 lines.
        assert!(lines.len() >= 7, "got {}", lines.len());
        for l in &lines {
            assert!((l.a.x - l.b.x).abs() > 1e-3); // horizontal lines
        }
    }

    #[test]
    fn lower_density_fewer_lines() {
        let c = square(1.0);
        let dense = generate_infill(&c, 1.0, 0.25, false, 0.0).len();
        let sparse = generate_infill(&c, 0.25, 0.25, false, 0.0).len();
        assert!(sparse < dense);
    }
}
