import type { FeatureNode } from "../state/types";

/**
 * Minimal browser-side FDM slicer preview for the current parametric model.
 *
 * This mirrors the Rust `tpt-vertex-slicer` pipeline (planar layering →
 * perimeter/wall offset → rectilinear infill) for the frontend's rectangular
 * extrusion model, producing a per-layer preview plus rough print estimates and
 * a G-code string. The authoritative slicer is the Rust crate (invoked via the
 * desktop `slice_model` Tauri command or WASM); this keeps the panel useful and
 * testable in a plain browser build without those backends wired in.
 */

export interface SliceSettings {
  layerHeight: number;
  firstLayerHeight: number;
  wallCount: number;
  /** Infill density fraction 0..1. */
  infillDensity: number;
  nozzleDiameter: number;
  material: string;
}

export const DEFAULT_SLICE_SETTINGS: SliceSettings = {
  layerHeight: 0.2,
  firstLayerHeight: 0.24,
  wallCount: 2,
  infillDensity: 0.2,
  nozzleDiameter: 0.4,
  material: "PLA",
};

export type Point = [number, number];

export interface LayerPreview {
  z: number;
  /** Closed perimeter loops (each an ordered list of XY points). */
  perimeters: Point[][];
  /** Infill segments as [x0, y0, x1, y1]. */
  infill: [number, number, number, number][];
}

export interface SliceResult {
  layers: LayerPreview[];
  gcode: string;
  layerCount: number;
  estimatedFilamentMm: number;
  estimatedTimeS: number;
  /** Bounding footprint width/depth/height in mm. */
  size: [number, number, number];
}

/** Extract the rectangular footprint and height from the feature list. */
export function modelBox(features: FeatureNode[]): {
  width: number;
  depth: number;
  height: number;
} {
  const sketch = features.find((f) => f.type === "sketch");
  const extrude = features.find((f) => f.type === "extrude");
  const x0 = Number(sketch?.params.x0 ?? 0);
  const y0 = Number(sketch?.params.y0 ?? 0);
  const x1 = Number(sketch?.params.x1 ?? 40);
  const y1 = Number(sketch?.params.y1 ?? 40);
  const height = Number(extrude?.params.height ?? 30);
  return {
    width: Math.abs(x1 - x0),
    depth: Math.abs(y1 - y0),
    height,
  };
}

/** Inset a centered rectangle by `d` on each side (clamped to non-negative). */
function insetRect(hw: number, hd: number, d: number): { hw: number; hd: number } {
  return { hw: Math.max(0, hw - d), hd: Math.max(0, hd - d) };
}

function rectLoop(hw: number, hd: number): Point[] {
  return [
    [-hw, -hd],
    [hw, -hd],
    [hw, hd],
    [-hw, hd],
  ];
}

/**
 * Slice the current model into a layer preview + G-code. Coordinates are
 * centered on the origin (matching the viewport mesh) and in millimetres.
 */
export function sliceModel(features: FeatureNode[], settings: SliceSettings): SliceResult {
  const { width, depth, height } = modelBox(features);
  const layers: LayerPreview[] = [];
  const gcodeLines: string[] = [];
  const extrusionWidth = settings.nozzleDiameter * 1.2;
  const filamentArea = Math.PI * (1.75 / 2) ** 2;
  const printSpeed = 60; // mm/s
  let eTotal = 0;
  let timeS = 0;

  gcodeLines.push(
    "; Generated by TPT Vertex slicer preview",
    `; Material: ${settings.material}`,
    "G90",
    "M82",
    "G21",
    "M104 S210",
    "M140 S60",
    "G28",
    "M109 S210",
    "M190 S60",
  );

  const hwOuter = width / 2;
  const hdOuter = depth / 2;

  // Layer Z positions: first layer, then uniform steps.
  const zs: number[] = [];
  let z = settings.firstLayerHeight;
  while (z <= height + 1e-9) {
    zs.push(Number(z.toFixed(4)));
    z += settings.layerHeight;
  }

  for (const layerZ of zs) {
    const perimeters: Point[][] = [];
    // Walls: outer boundary + nested insets.
    for (let w = 0; w < Math.max(1, settings.wallCount); w++) {
      const { hw, hd } = insetRect(hwOuter, hdOuter, extrusionWidth * (w + 0.5));
      if (hw <= 0 || hd <= 0) break;
      perimeters.push(rectLoop(hw, hd));
    }

    // Infill region = innermost wall.
    const innermostInset = extrusionWidth * (perimeters.length + 0.5);
    const region = insetRect(hwOuter, hdOuter, innermostInset);
    const infill: [number, number, number, number][] = [];
    if (settings.infillDensity > 0 && region.hw > 0 && region.hd > 0) {
      const spacing = extrusionWidth / settings.infillDensity;
      // Rectilinear lines alternating direction per layer.
      const horizontal = zs.indexOf(layerZ) % 2 === 0;
      if (horizontal) {
        for (let y = -region.hd; y <= region.hd + 1e-9; y += spacing) {
          infill.push([-region.hw, y, region.hw, y]);
        }
      } else {
        for (let x = -region.hw; x <= region.hw + 1e-9; x += spacing) {
          infill.push([x, -region.hd, x, region.hd]);
        }
      }
    }

    layers.push({ z: layerZ, perimeters, infill });

    // Emit G-code for this layer and accumulate estimates.
    gcodeLines.push(`; LAYER Z=${layerZ.toFixed(3)}`, `G1 Z${layerZ.toFixed(3)} F9000`);
    const beadArea = extrusionWidth * settings.layerHeight;
    const emitPath = (pts: Point[], closed: boolean) => {
      if (pts.length === 0) return;
      gcodeLines.push(`G1 X${pts[0][0].toFixed(3)} Y${pts[0][1].toFixed(3)} F9000`);
      const seq = closed ? [...pts, pts[0]] : pts;
      let prev = seq[0];
      for (let i = 1; i < seq.length; i++) {
        const p = seq[i];
        const d = Math.hypot(p[0] - prev[0], p[1] - prev[1]);
        eTotal += (beadArea * d) / filamentArea;
        timeS += d / printSpeed;
        gcodeLines.push(
          `G1 X${p[0].toFixed(3)} Y${p[1].toFixed(3)} E${eTotal.toFixed(4)} F${(printSpeed * 60).toFixed(0)}`,
        );
        prev = p;
      }
    };
    for (const loop of perimeters) emitPath(loop, true);
    for (const seg of infill) emitPath([[seg[0], seg[1]], [seg[2], seg[3]]], false);
  }

  gcodeLines.push("M104 S0", "M140 S0", "M84");

  return {
    layers,
    gcode: gcodeLines.join("\n") + "\n",
    layerCount: layers.length,
    estimatedFilamentMm: eTotal,
    estimatedTimeS: timeS,
    size: [width, depth, height],
  };
}
