name: 📝 Documentation
description: Report a docs issue or suggest documentation improvements
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: textarea
    id: location
    attributes:
      label: Location
      description: Which doc / file / section is affected?
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
